### ISSUE TITLE
Permission to fork

### ISSUE THREAD

**Issue by maxiride** [mazurio/bodyweight-fitness-android#29]
I love the minimalistic approach of your app which is really exercise oriented without useless popups, ads and other useless stuff present in most of other training apps. 

I'd like to fork the android app to modify it for a trx oriented workout. I've browsed a little the code and I guess I will just need to rename the exercises, modify the gifs url, YouTube urls, some menus etc but the core of the code doesn't need retouching. I've never done an android app but I'm familiar with most of the code language used, so I hope that just modifying the needed strings will do the job ^^

May I proceed with the fork?

**Comment by mazurio** [comment]
Hi @Maxiride 

Thanks for asking! You are free to go as this is the idea of sharing and open source but I would rather not see the fork published anywhere (so please keep it to your private use).

You can share the apk if you wish but please keep it advert free as the original source is.

**Modifying**
When it comes to modifying the app to suit your needs:

This is the file you are interested in:

https://github.com/mazurio/bodyweight-fitness-android/blob/master/app/src/main/res/raw/bodyweight_fitness_recommended_routine.json

If you change the packageId of the apk to something else than `com.bodyweight.fitness.free/pro` then you will be able to keep the id's of the exercises when you log the workouts without deleting your Bodyweight Fitness app from the phone.

You can just change the section names/category names and exercise names with descriptions here. The rest of the application is designed to keep up with the changes you make here. There is also code in the app to support multiple routines.

e.g. Molding Mobility is here https://github.com/mazurio/bodyweight-fitness-android/blob/master/app/src/main/res/raw/flexibility_molding_mobility.json

This code is 100% done but not enabled due to the fact that I wanted to improve downloading exercises later.

Just FYI, I am planning to start working on adding your own routines after I release and iOS update next week.

Thanks,
Damian

**Comment by maxiride** [comment]
Thanks for the infos and hint on how to modify the files! Really appreciated.

However I don't want to misunderstood the part "but I would rather not see the fork published anywhere (so please keep it to your private use)." Do you mean I can't fork it in a public viewable repo here on github? Or that I can't redistribuite the app -  for instance uploading it to the Play Store- ?

Thanks for the availabilty.

**Comment by mazurio** [comment]
I meant the play store/amazon store distribution - sorry for the confusion.
Hope thats all right?

Thanks,
Damian

**Comment by maxiride** [comment]
That's completly fine for me, however in case the workout program I'm planning to implement turns out to be good (based on the /r/bodyweightfitness guidelines) I would like to possibly discuss more in depth this limitation. I mean, why preventing other people to use it? (of course keeping it ads free and with proper credits to the author\link to the donation app etc)

But this is something I think we can postpone when I will be done making th fork.

**Comment by mazurio** [comment]
Sorry I was on my phone so I couldn't comment anymore. Yes, don't worry about not being able to publish it if you think it's worth it as long as it's ad free, it's still open source and with credits to the original version. There is LICENSE.md file which describes this in depth. The most important thing is not calling the app 'Bodyweight Fitness' and using the same logo. Apart that enjoy and good luck, let me know how it goes as I am going to actively work on the both Android & iOS to add more features and multiple workouts feature in the near future. @Maxiride

**Comment by maxiride** [comment]
@mazurio superfine ;) first of all I'll try to see how can I handle the situation.

**Comment by maxiride** [comment]
Just a last thing. Imho you should make the purchase a in app purchase instead of a separate download in the play store. This way you could keep a single download count and single rating score.

**Comment by mazurio** [comment]
I am actually just doing that for iOS :) - I am going to add as the next update to Android. Thanks!
